const countries = [
  { name: 'France', code: 'FR', phoneCode: '+33' },
  { name: 'United States', code: 'US', phoneCode: '+1' },
  { name: 'United Kingdom', code: 'GB', phoneCode: '+44' },
  { name: 'Germany', code: 'DE', phoneCode: '+49' },
  { name: 'Spain', code: 'ES', phoneCode: '+34' },
  { name: 'Italy', code: 'IT', phoneCode: '+39' },
  { name: 'Belgium', code: 'BE', phoneCode: '+32' },
  { name: 'Switzerland', code: 'CH', phoneCode: '+41' },
  { name: 'Netherlands', code: 'NL', phoneCode: '+31' },
  { name: 'Canada', code: 'CA', phoneCode: '+1' },
  { name: 'Australia', code: 'AU', phoneCode: '+61' },
  { name: 'China', code: 'CN', phoneCode: '+86' },
  { name: 'Japan', code: 'JP', phoneCode: '+81' },
  { name: 'India', code: 'IN', phoneCode: '+91' },
  { name: 'Brazil', code: 'BR', phoneCode: '+55' },
  { name: 'Russia', code: 'RU', phoneCode: '+7' },
  { name: 'South Africa', code: 'ZA', phoneCode: '+27' },
  { name: 'Mexico', code: 'MX', phoneCode: '+52' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54' },
  { name: 'Sweden', code: 'SE', phoneCode: '+46' },
  { name: 'Norway', code: 'NO', phoneCode: '+47' },
  { name: 'Denmark', code: 'DK', phoneCode: '+45' },
  { name: 'Finland', code: 'FI', phoneCode: '+358' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351' },
  { name: 'Greece', code: 'GR', phoneCode: '+30' },
  { name: 'Ireland', code: 'IE', phoneCode: '+353' },
  { name: 'Poland', code: 'PL', phoneCode: '+48' },
  { name: 'Austria', code: 'AT', phoneCode: '+43' },
  { name: 'Hungary', code: 'HU', phoneCode: '+36' },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '+420' },
];

export default countries;
